apiVersion: v1
kind: Pod
metadata:
  name: limesdr-srs-ue
spec:
  imagePullSecrets:
  - name: dockerhub-4141studio
  containers:
  - name: limesdr-srs-ue
    volumeMounts:
    - mountPath: /.config/srslte
      name: srs-ue-conf
    image: 4141studio/sdr-ubuntu-srslte-lime:v1
    imagePullPolicy: Always
    command: [ "sh", "-c", "sleep 12h" ]
    securityContext:
      privileged: true
  volumes:
  - name: srs-ue-conf
    hostPath:
      path: /etc/srs/ue
