apiVersion: v1
kind: Pod
metadata:
  name: testpod-srs-ue
spec:
  imagePullSecrets:
  - name: dockerhub-4141studio
  containers:
  - name: ue
    volumeMounts:
    - mountPath: /etc/srs/ue
      name: srs-ue-conf
    image: 4141studio/sdr-ubuntu-srslte-lime:v1
    imagePullPolicy: Always
    command: [ "sh", "-c", "sleep 12h" ]
    #command: [ "srsue", "/etc/srs/ue/ue.conf" ]
    securityContext:
      privileged: true
  volumes:
  - name: srs-ue-conf
    hostPath:
      path: /etc/srs/ue
