apiVersion: v1
kind: Pod
metadata:
  name: limesdr
spec:
  imagePullSecrets:
  - name: dockerhub-4141studio
  containers:
  - name: limesdr
    image: 4141studio/sdr-ubuntu-srslte-lime:v1
    imagePullPolicy: Always
    command: [ "sh", "-c", "sleep 1h" ]
    securityContext:
      privileged: true
