apiVersion: v1
kind: Pod
metadata:
  name: limesdr-local
spec:
  containers:
  - name: limesdr-local
    image: localhost:32000/sdr-ubuntu-srslte-lime:v1
    imagePullPolicy: Always
    command: [ "sh", "-c", "sleep 1h" ]
    securityContext:
      privileged: true
