apiVersion: v1
kind: Service
metadata:
  name: srsepc-srsenb-svc
  labels:
    app: srsepc-srsenb 
spec:
  ports:
  - port: 80
    name: srsepc-srsenb-web
  clusterIP: None
  selector:
    app: srsepc-srsenb 

---
apiVersion: apps/v1
kind: StatefulSet 
metadata:
  name: srsepc-srsenb-statefulset
  labels:
    app: srsepc-srsenb
spec:
  replicas: 1
  serviceName: srsepc-srsenb-svc
  selector:
    matchLabels:
      app: srsepc-srsenb
  template:
    metadata:
      labels:
        app: srsepc-srsenb
    spec:
      imagePullSecrets:
      - name: dockerhub-4141studio
      volumes:
      - name: enb-config
        configMap:
          name: srsenb-configmap 
      - name: epc-config
        configMap:
          name: srsepc-configmap 
      - name: enb-log
        emptyDir: {}
      containers:
      - name: enb-logger
        image: python:3.8.9-slim-buster
        volumeMounts:
        - name: enb-log
          mountPath: "/tmp/enb/"
        command: ["sh", "-c", "tail -f /tmp/enb/enb.log"]
      - name: enb
        image: localhost:32000/sdr-ubuntu-srslte-lime:0.0.4
        imagePullPolicy: Always
        volumeMounts:
        - name: enb-log
          mountPath: "/tmp/enb/"
        - name: enb-config
          mountPath: "/etc/srslte/"
        #command: [ "sh", "-c", "sleep 1h" ]
        command:
          - srsenb
          - /etc/srslte/enb.conf
          #- --rf.device_args=serial=00090726074D031F
          - --rf.device_args=serial=0009072C00D7311E 
          # 0009072C00D7311E is the one with soft antennas
          #- --enb_files.sib_config=sib.conf
        securityContext:
          privileged: true
      - name: epc
        image: localhost:32000/sdr-ubuntu-srslte-lime:0.0.4
        imagePullPolicy: Always
        volumeMounts:
        - name: epc-config
          mountPath: "/etc/srslte/"
        #command: [ "sh", "-c", "sleep 1h" ]
        command:
          - srsepc
          - /etc/srslte/epc.conf
        ports:
        - containerPort: 2152
        securityContext:
          privileged: true

