apiVersion: v1
kind: Service
metadata:
  name: srsue-svc
  labels:
    app: srsue 
spec:
  ports:
  - port: 80
    name: srsue-web
  clusterIP: None
  selector:
    app: srsue
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: srsue-statefulset
  labels:
    app: srsue
spec:
  replicas: 1
  serviceName: srsue-svc 
  selector:
    matchLabels:
      app: srsue 
  template:
    metadata:
      labels:
        app: srsue 
    spec:
      imagePullSecrets:
      - name: dockerhub-4141studio
      volumes:
      - name: config
        configMap:
          name: srsue-configmap
      containers:
      - name: ue
        image: localhost:32000/sdr-ubuntu-srslte-lime:0.0.3
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config
          mountPath: "/etc/srslte/"
          readOnly: false
        #command: [ "sh", "-c", "sleep 12h" ]
        command: 
        - srsue
        - /etc/srslte/ue.conf
        - --rf.device_args=serial=00090726074D031F
        #- --rf.device_args=serial=0009072C00D7311E 
        securityContext:
          privileged: true
