---
apiVersion: v1
kind: Pod
metadata:
  name: testpod-srsepc-srsenb
spec:
  imagePullSecrets:
  - name: dockerhub-4141studio
  volumes:
  - name: config
    configMap:
      name: srsenb-configmap 
  containers:
  - name: enb
    image: localhost:32000/sdr-ubuntu-srslte-lime:v2 
    imagePullPolicy: Always
    volumeMounts:
    - name: config
      mountPath: "/etc/srslte/"
    command: [ "sh", "-c", "sleep 1h" ]
    #command:
    #  - srsenb
    #  - /etc/srslte/enb.conf
    #  - --rf.device_args=serial=90726074D031F
    #  - --enb_files.sib_config=sib.conf
    securityContext:
      privileged: true
  - name: epc
    image: localhost:32000/sdr-ubuntu-srslte-lime:v2 
    imagePullPolicy: Always
    #command: [ "sh", "-c", "sleep 1h" ]
    command:
      - srsepc
      - /root/.config/srslte/epc.conf
    ports:
    - containerPort: 2152
    securityContext:
      privileged: true



