---
apiVersion: v1
kind: ConfigMap 
metadata:
  name: srsue-configmap
data:
  ue.conf: |
    [rf]
    dl_earfcn = 1720 
    freq_offset = 1000
    tx_gain = 60
    rx_gain = 60
    [pcap]
    enable = true
    filename = /tmp/ue.pcap
    #nas_enable = false
    #nas_filename = /tmp/nas.pcap
    [log]
    all_level = warning 
    phy_lib_level = none
    phy_level = info
    rf_level = info
    all_hex_limit = 32
    filename = /tmp/ue/ue.log
    file_max_size = -1
    [usim]
    mode = soft
    algo = milenage
    opc  = 63bfa50ee6523365ff14c1f45f88737d
    k    = 00112233445566778899aabbccddeeff
    imsi = 001480123456789
    imei = 353490069873319
    [rrc]
    ue_category   = 4
    release       = 8
    [nas]
    apn = internet
    #apn_protocol = ipv4
    #user = srsuser
    #pass = srspass
    #force_imsi_attach = false
    #eia = 1,2
    #eea = 0,1,2
    [gui]
    enable = false

