version: '2.2'
  
services:
  srsepc:
    container_name: srsepc
    build: .
    command:
      - srsepc
      - /root/.config/srslte/epc.conf
      - --mme.mme_bind_addr=10.80.95.10
      - --spgw.gtpu_bind_addr=10.80.95.10
    networks:
      corenet:
        ipv4_address: 10.80.95.10
    cap_add:
      - NET_ADMIN
      - SYS_NICE
    devices:
      - /dev/net/tun
  srsenb:
    container_name: virtual-srsenb
    build: .
    command:
      - srsenb
      - /root/.config/srslte/enb.conf
      - --enb.mme_addr=10.80.95.10
      - --enb.gtp_bind_addr=10.80.95.11
      - --enb.s1c_bind_addr=10.80.95.11
      - --enb_files.sib_config=sib.conf
    networks:
      corenet:
        ipv4_address: 10.80.95.11
    ipc: shareable
    cap_add:
      - SYS_NICE
      - NET_ADMIN
    # privileged to access USB3, cannot find USB device w.o privileged
    privileged: true

networks:
  corenet:
    ipam:
      driver: default
      config:
        - subnet: 10.80.95.0/24
